env:
  browser: true
  es6: true
  node: true
extends: 
  - 'eslint:recommended'
  - 'airbnb-base'
parserOptions:
  sourceType: module
rules:
  indent:
    - error
    - tab
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - always
